### ISSUE TITLE
issue 1

### ISSUE THREAD

**Issue by haniali1234** [geekwise-tiffany-ranish/dustybuns#10]
page: All
issue: navbar
photo:
![screen shot 2016-03-29 at 11 25 54 am](https://cloud.githubusercontent.com/assets/11038599/14119019/0e844e14-f5a1-11e5-9656-0942237fa903.png)

**Comment by geekwise-tiffany-ranish** [comment]
@haniali1234 fixed

**Comment by haniali1234** [comment]
![screen shot 2016-04-01 at 9 50 46 am](https://cloud.githubusercontent.com/assets/11038599/14213941/4ae27a98-f7ef-11e5-8947-e1124a28735f.png)

**Comment by geekwise-tiffany-ranish** [comment]
@haniali1234  fixed
