### ISSUE TITLE
nav button css issue

### ISSUE THREAD

**Issue by Sramos9191** [geekwise-tiffany-ranish/dustybuns#5]
issue: nav button css
page: global

how yours looks:
![screen shot 2016-03-23 at 2 09 49 pm](https://cloud.githubusercontent.com/assets/7436666/14001003/10bc444c-f101-11e5-8d55-1d99109109b3.png)

how it should look:
![screen shot 2016-03-23 at 2 10 05 pm](https://cloud.githubusercontent.com/assets/7436666/14001009/19d62e9e-f101-11e5-98d3-afe8f2c05d5b.png)

options:
add padding

**Comment by geekwise-tiffany-ranish** [comment]
text -align: center the li and fixed issue 

@Sramos9191 review

**Comment by Sramos9191** [comment]
perfect!
