### ISSUE TITLE
sf bistro page

### ISSUE THREAD

**Issue by geekwise-kao-thao** [geekwise-tiffany-ranish/dustybuns#8]
page: sf bistro
issue:  menu items missing, see photo

photo:

![image](https://cloud.githubusercontent.com/assets/17086853/14057079/126da37c-f2b3-11e5-8787-58b02bf8841a.png)

**Comment by geekwise-tiffany-ranish** [comment]
@geekwise-kao-thao please review fixed

**Comment by geekwise-kao-thao** [comment]
issue is still there

**Comment by geekwise-tiffany-ranish** [comment]
@geekwise-kao-thao review

**Comment by Alexg1021** [comment]
Looks complete! Please close out
